import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MuiTheme from '@/_lib/MuiTheme';
import HomeLayout from '@/layout';
import { Providers } from '@/redux/providers';
import { ToastContainer } from 'react-toastify';
import 'react-slideshow-image/dist/styles.css';
import { AppProvider } from '@/context';

export const metadata: Metadata = {
  title: 'Next basket',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppProvider>
            <MuiTheme>
              <ToastContainer />
              <HomeLayout>{children}</HomeLayout>
            </MuiTheme>
          </AppProvider>
        </Providers>
      </body>
    </html>
  );
}
